services: 
  5gc:
    container_name: open5gs_5gc
    build:
      context: open5gs
      target: open5gs
      args:
        OS_VERSION: "22.04"
        OPEN5GS_VERSION: "v2.7.0"
    env_file:
      - ${OPEN_5GS_ENV_FILE:-open5gs/open5gs.env}
    privileged: true
    ports:
      - "9999:9999/tcp"
    # Uncomment port to use the 5gc from outside the docker network
    #  - "38412:38412/sctp"
    #  - "2152:2152/udp"
    command: 5gc -c open5gs-5gc.yml
    healthcheck:
      test: [ "CMD-SHELL", "nc -z 127.0.0.20 7777" ]
      interval: 3s
      timeout: 1s
      retries: 60
    networks:
      ran:
        ipv4_address: ${OPEN5GS_IP:-10.53.1.2}

  oai:
    container_name: oai_gnb
    build:
      context: .
    command: /opt/openairinterface5g/cmake_targets/ran_build/build/nr-softmodem -O /gnb_config.conf
    networks:
      ran:
        ipv4_address: ${GNB_IP:-10.53.1.3}
    configs:
      - gnb_config.conf

networks:
  ran:
    ipam:
      driver: default
      config:
        - subnet: 10.53.1.0/24

configs:
  gnb_config.conf:
    file: ${GNB_CONFIG_PATH:-./gnb.} # Path to your desired config file
